app:
  build: ./app # EXPOSEs 80
  ports:
   - 8080:80 # Use 8080 to directly access the app over HTTP (skipping the proxy)
  volumes:
   - ./app:/app # Relative to Compose file
  environment:
   - ROOT_URL=https://local.cis-dev.brown.edu:3000
   - MONGO_URL=mongodb://db:27017/signmeup
   - VIRTUAL_HOST=local.cis-dev.brown.edu
   - ARGS=--settings settings.json --port 80 # Relative to project directory

db:
  ports:
   - 27071:27071

proxy:
  ports:
   - 80:80    # HTTP on 80
   - 3000:443 # HTTPS on 3000 to allow SAML to work